### ISSUE TITLE
include package is not being passed during distributed training

### ISSUE THREAD

**Issue by vikigenius** [himkt/allenopt#18]
Use distributed training like the following snippet

```
  "distributed": {
    "cuda_devices": if num_gpus > 1 then std.range(0, num_gpus - 1) else 0,
  },
```

The include-package option does not work for the allennlp tune command. My custom dataset_reader is not found. Adding the fully qualified class name solves this issue, which basically means for some reason include-package doesn't seem to work.

It works perfectly fine if i use the allennlp train command.

**Comment by himkt** [comment]
@vikigenius Thank you for trying allennlp-optuna and reporting the bug.

allennlp-optuna didn't pass `include-package` to Optuna correctly.
I made the PR #19 and released `v0.1.3`. Could you please give it a try with the latest allennlp-optuna?

**Comment by vikigenius** [comment]
~Yes, it works now. Thanks for the quick response and a very useful plugin.~

**Comment by vikigenius** [comment]
Actually, I was mistaken. It still throws an error in v0.1.3

**Comment by vikigenius** [comment]
The initial part works fine and datasets are read. But when the distributed training starts and multiple processes are started, all the processes throw the same error saying to include-package.

For some reason, these sub-processes are not getting the included package, even though the main process does. This does not happen with allennlp train

**Comment by himkt** [comment]
Thank you for the quick response. And I'm sorry to bother you.

> these sub-processes are not getting the included package, even though the main process does.

You're totally right. I found that we have to specify `include_package` in `train_mdoel` when distributed setting.
https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L406-L407

This is the problem of Optuna's AllenNLP integration. I made the PR to Optuna.
https://github.com/optuna/optuna/pull/2018

I'm afraid that please wait for some moments.

Or installing Optuna on my branch may work for you, for now.
(`pip uninstall optuna && pip install git+https://github.com/himkt/optuna@allennlp/include-package`)

**Comment by vikigenius** [comment]
@himkt thanks for the quick response, I also found another issue, that is probably also caused by upstream integration, but I want to confirm.

I tried to use the pruning capability by adding:

```
    epoch_callbacks: [
      {
        type: 'optuna_pruner',
      }
    ],
```

But it throws the error: https://github.com/optuna/optuna/blob/9d4dbb07063d0ae68f71b5f49dacccc048881472/optuna/integration/allennlp.py#L426-L434

Is there something different that needs to be done.

**Comment by himkt** [comment]
Let me create another issue for this. 👍

**Comment by JohnGiorgi** [comment]
@himkt

I am also facing this issue. During distributed optimization, an `allennlp.common.checks.ConfigurationError` error is thrown because AllenNLP can't find my registered classes (even though I pass the package with `--include-package`.

I tried installing your branch with: `pip install git+https://github.com/himkt/optuna@allennlp/include-package` but I get another error:

```bash
Collecting git+https://github.com/himkt/optuna@allennlp/include-package
  Cloning https://github.com/himkt/optuna (to revision allennlp/include-package) to /tmp/pip-req-build-p842z805
  WARNING: Did not find branch or tag 'allennlp/include-package', assuming revision or ref.
ERROR: Command errored out with exit status 1: git checkout -q allennlp/include-package Check the logs for full command output.
```

Does this branch still exist? Is there another branch I should be installing?

**Comment by himkt** [comment]
@JohnGiorgi I apologize for the inconvenience of the issue. Could you please try installing the latest Optuna with `pip install git+https://github.com/optuna/optuna@master`?

My patch (https://github.com/optuna/optuna/pull/2018) was merged to Optuna but still not included in the stable release. I think it works if you attempt to optimize hyperparameters without a pruning callback.

**Comment by JohnGiorgi** [comment]
@himkt That worked, thanks a lot!
