### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by h-vetinari** [himkt/allenopt#30]
Hey there, I'm [trying](https://github.com/conda-forge/staged-recipes/pull/13710) to repackage `allennlp-optuna` for conda-forge, and was wondering what the LICENSE of the package is?

Couldn't find anything in the repo. Conda-forge will not package something without a license, so I need to ask. :)

**Comment by himkt** [comment]
Hello @h-vetinari, thank you for reaching out!
I added the LICENSE (MIT LICENSE) in #31. 😸

**Comment by h-vetinari** [comment]
Thanks! :)
