### ISSUE TITLE
retrain command not getting environment values

### ISSUE THREAD

**Issue by pvcastro** [himkt/allenopt#41]
Hi @himkt !

I think I saw another issue, now with the `retrain` command. It's not getting any value set to the environment variables, except the ones that are actually from the best params used for training. This works with the `tune` command, probably because it uses `AllenNLPExecutor`, and this executor sets up the configuration properly, fetching all environment variables in the `_build_params` method.

Without this, I keep getting `RUNTIME ERROR: Undefined external variable: x` errors from jsonnet, for any environment variables that were expected in my jsonnet config.

**Comment by himkt** [comment]
Thank you for reporting. You're totally right. This bug was introduced in https://github.com/himkt/allennlp-optuna/pull/37, which evaluates jsonnet before invoking `allennlp.commands.train.train_model_from_file`. I'll fix it.

**Comment by himkt** [comment]
Sorry for being late @pvcastro. Optuna v2.8.0 was released and it solves this problem.
Please upgrade Optuna to your environment and install the latest version of Optuna.

**Comment by pvcastro** [comment]
Thanks @himkt !

**Comment by himkt** [comment]
Let me close the issue.
